table Dados
	lineageTag: 872cf256-3b5e-4112-b635-dcc891c072ce

	measure 'Total Pacientes' = COUNTROWS(Dados)
		formatString: 0
		lineageTag: 7b39e5c6-4e10-4032-aa62-437d5ff902c9

	measure 'Média Melhora' = AVERAGE(Dados[Melhora (%)])
		lineageTag: 8d9e6b11-1750-4c78-a800-29b5f5c2bcf1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Sessões' = AVERAGE(Dados[Sessões])
		lineageTag: c192460f-d2bf-4407-8372-d30a6b1c4540

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Melhor Paciente' = VAR MaxMelhora = MAX(Dados[Melhora (%)]) RETURN CALCULATE(   FIRSTNONBLANK(Dados[Paciente], 1),   Dados[Melhora (%)] = MaxMelhora )
		lineageTag: a2112628-7e6c-4ebd-8639-1dc67c2614cb

	measure 'Melhor Condição' = ```
			
			VAR TabelaResumo = 
			    SUMMARIZE(
			        Dados,
			        Dados[Condição],
			        "MediaMelhora", AVERAGE(Dados[Melhora (%)])
			    )
			VAR MaiorMedia = 
			    MAXX(TabelaResumo, [MediaMelhora])
			RETURN
			    MAXX(
			        FILTER(TabelaResumo, [MediaMelhora] = MaiorMedia),
			        Dados[Condição]
			    )
			```
		lineageTag: 2a296c44-9e6c-43a9-8d74-8a2778ac67fa

	measure 'Correlação Sessões Melhora' = VAR MeanX = AVERAGE(Dados[Sessões]) VAR MeanY = AVERAGE(Dados[Melhora (%)]) RETURN DIVIDE(   SUMX(Dados, (Dados[Sessões]-MeanX)*(Dados[Melhora (%)]-MeanY)),   SQRT(     SUMX(Dados, (Dados[Sessões]-MeanX)^2) *     SUMX(Dados, (Dados[Melhora (%)]-MeanY)^2)   ) )
		lineageTag: 78d5d221-175e-411a-9880-f9184ba9c14e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Correlação =
			
			VAR MeanX = AVERAGE(Dados[Sessões])
			VAR MeanY = AVERAGE(Dados[Melhora (%)])
			RETURN
			DIVIDE(
			    SUMX(Dados, (Dados[Sessões] - MeanX) * (Dados[Melhora (%)] - MeanY)),
			    SQRT(
			        SUMX(Dados, (Dados[Sessões] - MeanX) ^ 2) *
			        SUMX(Dados, (Dados[Melhora (%)] - MeanY) ^ 2)
			    )
			)
		formatString: 0.0000
		lineageTag: fbaed182-761c-47ee-be1d-85d6defe9185

	column Paciente
		dataType: string
		lineageTag: bb17f161-98ec-4438-9e7d-5ce46539fef2
		summarizeBy: none
		sourceColumn: Paciente

		annotation SummarizationSetBy = Automatic

	column Idade
		dataType: int64
		formatString: 0
		lineageTag: 435dfe81-f4e8-48fe-991b-c659ac36d5b7
		summarizeBy: none
		sourceColumn: Idade

		annotation SummarizationSetBy = User

	column Condição
		dataType: string
		lineageTag: 4becd16a-8d6e-4532-9377-4fb3b9416e84
		summarizeBy: none
		sourceColumn: Condição

		annotation SummarizationSetBy = Automatic

	column Sessões
		dataType: int64
		formatString: 0
		lineageTag: f78fedc5-f792-4826-ab3b-9374ed1c8979
		summarizeBy: none
		sourceColumn: Sessões

		annotation SummarizationSetBy = User

	column 'Melhora (%)'
		dataType: int64
		formatString: 0
		lineageTag: 78b52437-7f2d-478d-9f29-1200f2890c77
		summarizeBy: none
		sourceColumn: Melhora (%)

		annotation SummarizationSetBy = User

	partition Dados = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("XU69DsIgEH4X5g4Ui7ISG6ONJg5uhIEIQ5PmaCB9Il/BN+iLyXGDCcvl7rvvzxg2xf0TWccGWcYY1hRyJkTwMo6c2c6wh0uzK+cBMQ15Dt75UPYeZQORzi4tMZdbIusGef9CVfWcpEjSgIhQZbxGfcUdLU70fQafIsU2bWqyIta0LdRGtm0UpSPpvr1dpnL/KIHesv4vIYEDjz5SNn0FmVv7Aw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Paciente = _t, Idade = _t, Condição = _t, Sessões = _t, #"Melhora (%)" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Paciente", type text}, {"Idade", Int64.Type}, {"Condição", type text}, {"Sessões", Int64.Type}, {"Melhora (%)", Int64.Type}})
				in
				    #"Tipo Alterado"

	changedProperty = Name

	annotation PBI_ResultType = Table

